# Returns the names of actors with count of the actors that have appeared in more than christopher nolan movies 

SELECT DISTINCT ?actor (COUNT(?film) AS ?numFilms)
WHERE {
  ?film_ wdt:P31 wd:Q11424 .        # find all movies
  ?film_ wdt:P57 wd:Q25191 .
  ?film_ wdt:P161 ?actor_ .  
  ?film_ rdfs:label ?film .
  ?actor_ rdfs:label ?actor 
  filter (lang(?film) = "en").  
  filter (lang(?actor) = "en").  
}
GROUP BY ?actor
HAVING (1 < ?numFilms)  
LIMIT 100